guru:
    jms:
      username: JMS Username
      password: somepass
      url: someURL

---
spring:
  config:
    activate:
      on-profile: de
guru:
    jms:
      username: JMS Username $$$$$ German
